### ISSUE TITLE
On Windows pkcs11 module error with new version 2.4.0

### ISSUE THREAD

**Issue by figolino** [Yubico/yubihsm-shell#313]
After updating from 2.3.2 to 2.4.0 PKCS11 operation are failing with this error.

if i roll back to 2.3.2 operation is working.

Tested with openSC and with java programm sunPKCS11

```
PS C:\Program Files\OpenSC Project\OpenSC\tools> .\pkcs11-tool.exe --module "C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll" --id 0003 -s -p bb98Change4It -m RSA-PKCS --input-file "C:\workspace\yubihsm2-sdk\data.txt" --output-file "C:\workspace\yubihsm2-sdk\data.sig"
**sc_dlopen failed: LoadLibrary/GetProcAddress failed**
error: Failed to load pkcs11 module
Aborting.
```

```
PS C:\Program Files\OpenSC Project\OpenSC\tools> $env:YUBIHSM_PKCS11_CONF
C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.conf
```

**content of config yubihsm_pkcs11.conf**
*******************************************
```
# This is a sample configuration file for the YubiHSM PKCS#11 module
# Uncomment the various options as needed

# URL of the connector to use. This can be a comma-separated list
connector = http://192.168.1.80:12345

# Enables general debug output in the module
....
```

**connector status:**
```
status=OK
serial=*
version=3.0.4
pid=2624
address=192.168.1.80
port=12345
```

**Enviroment Variables:**

```
PS C:\Program Files\OpenSC Project\OpenSC\tools> $env:path
C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files (x86)\dotnet\;C:\Program Files\Amazon\AWSCLIV2\;C:\Ruby26-x64\bin;C:\Users\mariu\AppData\Local\Microsoft\WindowsApps;C:\Users\mariu\.dotnet\tools;C:\Users\mariu\AppData\Roaming\npm;C:\Users\mariu\AppData\Local\Yarn\bin;C:\Users\mariu\AppData\Local\Android\Sdk\platform-tools;C:\adb;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\Yubico\YubiHSM Shell\bin;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Ruby26-x64\bin;C:\Users\mariu\AppData\Local\Microsoft\WindowsApps;C:\Users\mariu\.dotnet\tools;C:\Users\mariu\.dotnet\tools;C:\Users\mariu\AppData\Roaming\npm;C:\Users\mariu\AppData\Local\Yarn\bin;C:\Users\mariu\AppData\Local\Microsoft\WindowsApps;C:\Users\mariu\AppData\Local\Android\Sdk\platform-tools;
```

**Output of Java Application with sunPKCS11 with new shell version 2.4.0**

```
"C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe" -Djava.security.debug=sunpkcs11,pkcs11keystore "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.3\lib\idea_rt.jar=53505:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.3\bin" -Dfile.encoding=UTF-8 -classpath C:\workspace\PKCS_11Client\out\production\PKCS_11Client PKCS11
YUBIHSM_PKCS11_CONF: C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.conf
SunPKCS11 loading sun_yubihsm2_pkcs11.conf
sunpkcs11: Initializing PKCS#11 library C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll
Exception in thread "main" java.security.ProviderException: Initialization failed
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:381)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:112)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:109)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:109)
	at PKCS11.main(PKCS11.java:32)
Caused by: java.io.IOException: Die angegebene Prozedur wurde nicht gefunden.
C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.connect(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:147)
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:160)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:318)
	... 5 more
```

**Output of Java Application with sunPKCS11 with old Shell version 2.3.2**

```
"C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin\java.exe" -Djava.security.debug=sunpkcs11,pkcs11keystore "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.3\lib\idea_rt.jar=53676:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2.3\bin" -Dfile.encoding=UTF-8 -classpath C:\workspace\PKCS_11Client\out\production\PKCS_11Client PKCS11
YUBIHSM_PKCS11_CONF: C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.conf
SunPKCS11 loading sun_yubihsm2_pkcs11.conf
sunpkcs11: Initializing PKCS#11 library C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll
Information for provider SunPKCS11-yubiHSM2-pkcs11
Library info:
  cryptokiVersion: 2.40
  manufacturerID: Yubico (www.yubico.com)         
  flags: 0
  libraryDescription: YubiHSM PKCS#11 Library         
  libraryVersion: 2.32
All slots: 0
Slots with tokens: 0
Slot info for slot 0:
  slotDescription: YubiHSM Connector 192.168.1.80                                  
  manufacturerID: Yubico                          
  flags: CKF_TOKEN_PRESENT | CKF_REMOVABLE_DEVICE | CKF_HW_SLOT
  hardwareVersion: 3.04
  firmwareVersion: 3.04
Token info for token in slot 0:
  label: YubiHSM                         
  manufacturerID: Yubico (www.yubico.com)         
  model: YubiHSM         
  serialNumber: 18951309        
  flags: CKF_RNG | CKF_LOGIN_REQUIRED | CKF_USER_PIN_INITIALIZED | CKF_TOKEN_INITIALIZED
  ulMaxSessionCount: CK_EFFECTIVELY_INFINITE
  ulSessionCount: CK_UNAVAILABLE_INFORMATION
  ulMaxRwSessionCount: CK_EFFECTIVELY_INFINITE
  ulRwSessionCount: CK_UNAVAILABLE_INFORMATION
  ulMaxPinLen: 68
  ulMinPinLen: 12
  ulTotalPublicMemory: CK_UNAVAILABLE_INFORMATION
  ulFreePublicMemory: CK_UNAVAILABLE_INFORMATION
  ulTotalPrivateMemory: CK_UNAVAILABLE_INFORMATION
  ulFreePrivateMemory: CK_UNAVAILABLE_INFORMATION
  hardwareVersion: 2.200
  firmwareVersion: 2.200
  utcTime: ÈBu   ïÊå  
Mechanism CKM_RSA_PKCS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 11009 = CKF_HW | CKF_ENCRYPT | CKF_DECRYPT | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA1_RSA_PKCS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA256_RSA_PKCS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA384_RSA_PKCS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA512_RSA_PKCS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_RSA_PKCS_PSS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA1_RSA_PKCS_PSS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA256_RSA_PKCS_PSS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA384_RSA_PKCS_PSS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA512_RSA_PKCS_PSS:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_RSA_PKCS_KEY_PAIR_GEN:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 65537 = CKF_HW | CKF_GENERATE_KEY_PAIR
Mechanism CKM_EC_KEY_PAIR_GEN:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26279937 = CKF_HW | CKF_GENERATE_KEY_PAIR | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_SHA_1_HMAC:
  ulMinKeySize: 1
  ulMaxKeySize: 512
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_GENERIC_SECRET_KEY_GEN:
  ulMinKeySize: 1
  ulMaxKeySize: 1024
  flags: 32769 = CKF_HW | CKF_GENERATE
Mechanism CKM_SHA256_HMAC:
  ulMinKeySize: 1
  ulMaxKeySize: 512
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA384_HMAC:
  ulMinKeySize: 1
  ulMaxKeySize: 1024
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_SHA512_HMAC:
  ulMinKeySize: 1
  ulMaxKeySize: 1024
  flags: 10241 = CKF_HW | CKF_SIGN | CKF_VERIFY
Mechanism CKM_ECDSA:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26224641 = CKF_HW | CKF_SIGN | CKF_VERIFY | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDSA_SHA1:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26224641 = CKF_HW | CKF_SIGN | CKF_VERIFY | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDH1_DERIVE:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26738689 = CKF_HW | CKF_DERIVE | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_RSA_PKCS_OAEP:
  ulMinKeySize: 2048
  ulMaxKeySize: 4096
  flags: 769 = CKF_HW | CKF_ENCRYPT | CKF_DECRYPT
Mechanism (Vendor-Specific) 0x00000000D9554204:
  ulMinKeySize: 128
  ulMaxKeySize: 256
  flags: 393985 = CKF_HW | CKF_ENCRYPT | CKF_DECRYPT | CKF_WRAP | CKF_UNWRAP
Mechanism CKM_ECDSA_SHA256:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26224641 = CKF_HW | CKF_SIGN | CKF_VERIFY | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDSA_SHA384:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26224641 = CKF_HW | CKF_SIGN | CKF_VERIFY | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_ECDSA_SHA512:
  ulMinKeySize: 224
  ulMaxKeySize: 521
  flags: 26224641 = CKF_HW | CKF_SIGN | CKF_VERIFY | CKF_EC_F_P | CKF_EC_NAMEDCURVE | CKF_EC_UNCOMPRESS
Mechanism CKM_SHA_1:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_SHA256:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_SHA384:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
Mechanism CKM_SHA512:
  ulMinKeySize: 0
  ulMaxKeySize: 0
  flags: 1024 = CKF_DIGEST
sunpkcs11: login succeeded
Token Alias Map:
  certificate	type=[private key]
	label=[certificate]
	id=0x0003
	trusted=[false]
	matched=[true]
	cert=[	subject: CN=XXXX, OU=XXX, O=XXX, C=CH
		issuer: CN=XXXXXXX, OU=XXXXXXX, OU=XXXX, O=XXXX, C=CH
		serialNum: 99053697531669918395086896831506597902]
certificate
pkcs11keystore: P11KeyStore load. Entry count: 1
Decrypted data:[84, 101, 115, 116, 32, 115, 116, 114, 105, 110, 103, 32, 116, 111, 32, 101, 110, 99, 114, 121, 112, 116]

Process finished with exit code 0
```

**Comment by aveenismail** [comment]
This looks a lot like the PKCS11 module was not found. Did you update the system path to point to the new libraries? Both libyubihsm and libcrypt need to be on the system path for the application to find the pkcs11 module.

**Comment by qpernil** [comment]
To clarify - there _should_ be no difference between the releases in this regard, i.e. both versions require C:\Program Files\Yubico\YubiHSM Shell\bin\ to be in your path, in order to find all dependencies for yubihsm_pkcs11.dll

**Comment by figolino** [comment]
Thanks for looking at the problem quickly. 

As can be seen above (export path) the libs are on the path. 
```

PS C:\Program Files\OpenSC Project\OpenSC\tools> $env:path
.......;C:\Program Files\Yubico\YubiHSM Shell\bin;.....

```

Unfortunately, it seems only with the new version it doesen't work. if I install the old on the same system it runs again.

I have checked it several times.

**Comment by figolino** [comment]
Hi aveenismail

Yes this solved the problem.
thanks
